### ISSUE TITLE
can't run playground

### ISSUE THREAD

**Issue by LoTwT** [webfansplz/temir#5]
Project Info:

```bash
- Operating System:  `Windows_NT`
- Node Version:      `v16.16.0`
- Package Manager:   `pnpm@7.9.0`
- Terminal:          `PowerShell 7.2.5`
```

Logs:

```bash
temir\playground on  main [?] via 🌰 v16.16.0 
❯ pnpm dev

> @temir/playground@ dev G:\codes\temir\playground
> temir main.ts

G:\codes\temir\node_modules\.pnpm\yoga-layout-prebuilt@1.10.0\node_modules\yoga-layout-prebuilt\yoga-layout\build\Release\nbind.js:53
        throw ex;
        ^

TypeError: Cannot convert a Symbol value to a string
    at Array.join (<anonymous>)
    at warn (G:\codes\temir\node_modules\.pnpm\@vue+runtime-core@3.2.37\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:24:24)
    at patch (G:\codes\temir\node_modules\.pnpm\@vue+runtime-core@3.2.37\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:4987:21)
    at mountChildren (G:\codes\temir\node_modules\.pnpm\@vue+runtime-core@3.2.37\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:5163:13)
    at mountElement (G:\codes\temir\node_modules\.pnpm\@vue+runtime-core@3.2.37\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:5073:17)
    at processElement (G:\codes\temir\node_modules\.pnpm\@vue+runtime-core@3.2.37\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:5055:13)
    at patch (G:\codes\temir\node_modules\.pnpm\@vue+runtime-core@3.2.37\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:4975:21)
    at ReactiveEffect.componentUpdateFn [as fn] (G:\codes\temir\node_modules\.pnpm\@vue+runtime-core@3.2.37\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:5515:21)
    at ReactiveEffect.run (G:\codes\temir\node_modules\.pnpm\@vue+reactivity@3.2.37\node_modules\@vue\reactivity\dist\reactivity.cjs.js:189:25)
    at instance.update (G:\codes\temir\node_modules\.pnpm\@vue+runtime-core@3.2.37\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:5622:56)
 ELIFECYCLE  Command failed with exit code 7.
```

**Comment by webfansplz** [comment]
use yarn/npm instead of pnpm install (to avoid the PNPM workspace) for playground  then run again.

**Comment by webfansplz** [comment]
Let’s track in #3
