### ISSUE TITLE
Support vue 3 jsx/tsx?

### ISSUE THREAD

**Issue by Innei** [webfansplz/temir#6]
Hello, this is awesome project to write cli toolchain. When I try to write a demo, I run into problems. This is my code.

```ts
import { render } from '@temir/core'

import App from './views/App'

render(App)
```

```
// App.tsx
import { TText } from '@temir/core'
import { TBox } from '@temir/core'
import { defineComponent } from 'vue'

export default defineComponent({
  setup() {
    return () => (
      <TBox>
        <TText>Hello World!</TText>
      </TBox>
    )
  },
})

```

And run dev then crashed...

```

> @innei/bump-version@0.3.1 dev /Users/user/git/bump-version
> temir src/main.ts

/Users/user/git/bump-version/node_modules/.pnpm/yoga-layout-prebuilt@1.10.0/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

TypeError: Cannot read properties of undefined (reading 'modules')
    at comp.setup (/Users/user/git/bump-version/__vue-jsx-ssr-register-helper:8:18)
    at callWithErrorHandling (/Users/user/git/bump-version/node_modules/.pnpm/@vue+runtime-core@3.2.37/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:157:22)
    at setupStatefulComponent (/Users/user/git/bump-version/node_modules/.pnpm/@vue+runtime-core@3.2.37/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:7084:29)
    at setupComponent (/Users/user/git/bump-version/node_modules/.pnpm/@vue+runtime-core@3.2.37/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:7039:11)
    at mountComponent (/Users/user/git/bump-version/node_modules/.pnpm/@vue+runtime-core@3.2.37/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:5401:13)
    at processComponent (/Users/user/git/bump-version/node_modules/.pnpm/@vue+runtime-core@3.2.37/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:5376:17)
    at patch (/Users/user/git/bump-version/node_modules/.pnpm/@vue+runtime-core@3.2.37/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:4978:21)
    at ReactiveEffect.componentUpdateFn [as fn] (/Users/user/git/bump-version/node_modules/.pnpm/@vue+runtime-core@3.2.37/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:5515:21)
    at ReactiveEffect.run (/Users/user/git/bump-version/node_modules/.pnpm/@vue+reactivity@3.2.37/node_modules/@vue/reactivity/dist/reactivity.cjs.js:189:25)
    at instance.update (/Users/user/git/bump-version/node_modules/.pnpm/@vue+runtime-core@3.2.37/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:5622:56)
```

Help,

**Comment by webfansplz** [comment]
Supported in V0.0.10
